# Generated by Django 4.0.3 on 2022-09-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='weather',
            field=models.TextField(null=True),
        ),
    ]
