# Generated by Django 4.0.3 on 2022-09-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_conference_temperature_conference_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='weather',
        ),
    ]
